// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	"github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"
)

// NewMatcher creates a new instance of Matcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Matcher {
	mock := &Matcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Matcher is an autogenerated mock type for the Matcher type
type Matcher struct {
	mock.Mock
}

type Matcher_Expecter struct {
	mock *mock.Mock
}

func (_m *Matcher) EXPECT() *Matcher_Expecter {
	return &Matcher_Expecter{mock: &_m.Mock}
}

// FilterApps provides a mock function for the type Matcher
func (_mock *Matcher) FilterApps(ctx context.Context, logCtx *logrus.Entry, filter v1alpha1.ApplicationSetFilter, apps []v1alpha1.Application) ([]v1alpha1.Application, error) {
	ret := _mock.Called(ctx, logCtx, filter, apps)

	if len(ret) == 0 {
		panic("no return value specified for FilterApps")
	}

	var r0 []v1alpha1.Application
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *logrus.Entry, v1alpha1.ApplicationSetFilter, []v1alpha1.Application) ([]v1alpha1.Application, error)); ok {
		return returnFunc(ctx, logCtx, filter, apps)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *logrus.Entry, v1alpha1.ApplicationSetFilter, []v1alpha1.Application) []v1alpha1.Application); ok {
		r0 = returnFunc(ctx, logCtx, filter, apps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1alpha1.Application)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *logrus.Entry, v1alpha1.ApplicationSetFilter, []v1alpha1.Application) error); ok {
		r1 = returnFunc(ctx, logCtx, filter, apps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Matcher_FilterApps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterApps'
type Matcher_FilterApps_Call struct {
	*mock.Call
}

// FilterApps is a helper method to define mock.On call
//   - ctx context.Context
//   - logCtx *logrus.Entry
//   - filter v1alpha1.ApplicationSetFilter
//   - apps []v1alpha1.Application
func (_e *Matcher_Expecter) FilterApps(ctx interface{}, logCtx interface{}, filter interface{}, apps interface{}) *Matcher_FilterApps_Call {
	return &Matcher_FilterApps_Call{Call: _e.mock.On("FilterApps", ctx, logCtx, filter, apps)}
}

func (_c *Matcher_FilterApps_Call) Run(run func(ctx context.Context, logCtx *logrus.Entry, filter v1alpha1.ApplicationSetFilter, apps []v1alpha1.Application)) *Matcher_FilterApps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *logrus.Entry
		if args[1] != nil {
			arg1 = args[1].(*logrus.Entry)
		}
		var arg2 v1alpha1.ApplicationSetFilter
		if args[2] != nil {
			arg2 = args[2].(v1alpha1.ApplicationSetFilter)
		}
		var arg3 []v1alpha1.Application
		if args[3] != nil {
			arg3 = args[3].([]v1alpha1.Application)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Matcher_FilterApps_Call) Return(applications []v1alpha1.Application, err error) *Matcher_FilterApps_Call {
	_c.Call.Return(applications, err)
	return _c
}

func (_c *Matcher_FilterApps_Call) RunAndReturn(run func(ctx context.Context, logCtx *logrus.Entry, filter v1alpha1.ApplicationSetFilter, apps []v1alpha1.Application) ([]v1alpha1.Application, error)) *Matcher_FilterApps_Call {
	_c.Call.Return(run)
	return _c
}
