apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL:  https://github.com/gdsoumya/argo-cd.git
        revision: gdsoumya-patch-1
        files:
        - path: "applicationset/examples/git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{.cluster.name}}-{{.automated.prune | not | not}}-guestbook'
    spec:
      syncPolicy:
       automated:
        prune: '{{.automated.prune}}'
      project: default
      source:
        repoURL: https://github.com/gdsoumya/argo-cd.git
        targetRevision: gdsoumya-patch-1
        path: "applicationset/examples/git-generator-files-discovery/apps/guestbook"
      destination:
        server: https://kubernetes.default.svc
        #server: '{{.cluster.address}}'
        namespace: guestbook
      
